CineManager/CineManager/Controllers/FilmeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineManager.Data;
using CineManager.Models;
using Microsoft.AspNetCore.Authorization;
using CineManager.Areas.Identity.Pages.Account.Manage;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.WebUtilities;
using System.IO;
using PdfSharpCore.Drawing;

namespace CineManager.Controllers
{
    public class FilmeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilmeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Filme
        public async Task<IActionResult> Index()
        {
            InserirDados();

            return View(await _context.Filme.Include(x => x.Generos).
                Include(x => x.TiposFilme).OrderBy(x => x.Lancamento).Where(x => 
                (x.Lancamento < DateTime.Now && x.EmCartazAte > DateTime.Now)).ToListAsync());
        }

        // GET: Filme/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.Include(x => x.Generos).ThenInclude(x => x.Genero).Include(x => x.TiposFilme).ThenInclude(x => x.TipoFilme).
                    FirstOrDefaultAsync(x => x.Id == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // GET: Filme/Create
        public IActionResult Create()
        {
            List<Genero> listaGeneros = _context.Generos.ToList();
            List<TipoFilme> listaTipos = _context.TipoFilmes.ToList();
            ViewBag.ListaTipos = listaTipos;

            if (listaGeneros.Count > 0)
                listaGeneros.OrderBy(x => x.Nome);
            ViewBag.ListaGeneros = listaGeneros;
            return View();
        }

        // POST: Filme/Create    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Filme filme)
        {
            if (ModelState.IsValid)
            {
                foreach (var gen in filme.ListaGenerosJoin.Split(','))
                {
                    int generoId = Convert.ToInt32(gen);
                    Genero genero = await _context.Generos.FirstOrDefaultAsync(x => x.Id == generoId);
                    FilmeGenero filmGen = new FilmeGenero();
                    filmGen.Genero = genero;
                    filme.Generos.Add(filmGen);
                }

                foreach (var tipo in filme.ListaTiposJoin.Split(','))
                {
                    int tipoId = Convert.ToInt32(tipo);
                    TipoFilme tipoFilme = await _context.TipoFilmes.FirstOrDefaultAsync(x => x.Id == tipoId);
                    FilmeTipoFilme filmeTipo = new FilmeTipoFilme();
                    filmeTipo.TipoFilme = tipoFilme;
                    filme.TiposFilme.Add(filmeTipo);
                }


                _context.Add(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: Filme/Edit/5
        //[Route("Filme/{id:int}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = _context.Filme.Include(x => x.Generos).ThenInclude(gen => gen.Genero).
                Include(x => x.TiposFilme).ThenInclude(x => x.TipoFilme).FirstOrDefault(x => x.Id == id);


            if (filme == null)
            {
                return NotFound();
            }

            var genSelecionados = new List<int>();
            foreach (var gen in filme.Generos)
            {
                genSelecionados.Add(gen.Genero.Id);
            }

            var tiposSelecionados = new List<int>();

            foreach (var tipo in filme.TiposFilme)
            {
                tiposSelecionados.Add(tipo.TipoFilme.Id);
            }

            filme.ListaGenerosJoinPreserve = string.Join(',', genSelecionados);
            filme.ListaTiposRemove = string.Join(',', tiposSelecionados);

            ViewBag.ListaTipoFilmes = _context.TipoFilmes.ToListAsync();
            ViewBag.ListaGeneros = _context.Generos.ToListAsync();

            return View(filme);
        }

        // POST: Filme/Edit/5    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [FromForm] Filme filme)
        {
            if (id != filme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    foreach (var gen in filme.ListaGenerosJoinPreserve.Split(','))
                    {
                        var genInt = Convert.ToInt32(gen);
                        var filGen = await _context.FilmeGeneros.Include(x => x.Genero).FirstOrDefaultAsync(x => x.Genero.Id == genInt);
                        if (filGen != null)
                        {
                            filme.Generos.Remove(filGen);
                            _context.Remove(filGen);
                        }
                    }

                    //Se editar um filme e não abrir as modais e clicar em salvar, estoura excessão. Precisa tratar!!!

                    foreach (var gen in filme.ListaGenerosJoin.Split(','))
                    {
                        var genInt = Convert.ToInt32(gen);
                        var genero = await _context.Generos.FirstOrDefaultAsync(x => x.Id == genInt);
                        filme.Generos.Add(new FilmeGenero() { Genero = genero });
                    }

                    foreach (var tipo in filme.ListaTiposRemove.Split(','))
                    {
                        var tipoInt = Convert.ToInt32(tipo);
                        var filmeTipo = await _context.FilmeTiposFilme.Include(x => x.TipoFilme).FirstOrDefaultAsync(x => x.TipoFilme.Id == tipoInt);
                        if (filmeTipo != null)
                        {
                            filme.TiposFilme.Remove(filmeTipo);
                            _context.Remove(filmeTipo);
                        }
                    }

                    foreach (var tipo in filme.ListaTiposJoin.Split(','))
                    {
                        var tipoInt = Convert.ToInt32(tipo);
                        var tipos = await _context.TipoFilmes.FirstOrDefaultAsync(x => x.Id == tipoInt);
                        filme.TiposFilme.Add(new FilmeTipoFilme() { TipoFilme = tipos });
                    }

                    _context.Update(filme);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: Filme/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.Include(x => x.Generos).Include(x => x.TiposFilme).
                   FirstOrDefaultAsync(x => x.Id == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        public ActionResult DeleteFilme(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = _context.Filme.Include(x => x.Generos).Include(x => x.TiposFilme).
                   FirstOrDefault(x => x.Id == id);
            if (filme == null)
            {
                return NotFound();
            }

            foreach (var item in filme.Generos)
            {
                _context.Remove(item);
            }

            foreach (var item in filme.TiposFilme)
            {
                _context.Remove(item);
            }
            _context.Remove(filme);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index)); ;
        }


        // POST: Filme/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filme = await _context.Filme.Include(x => x.Generos).Include(x => x.TiposFilme).
                FirstOrDefaultAsync(x => x.Id == id);

            if (filme == null)
            {
                return NotFound();
            }

            _context.Filme.Remove(filme);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult GenerosFilme()
        {
            List<Genero> generos = _context.Generos.ToList();
            this.ViewBag._ListaGeneros = generos.OrderBy(x => x.Nome);

            return PartialView("../Shared/Modais/GenerosResult");
        }

        public async Task<ActionResult> GenerosFilmeEdit(int id)
        {
            List<Genero> generos = _context.Generos.ToList();
            var filme = await _context.Filme.Include(x => x.Generos).
             FirstOrDefaultAsync(x => x.Id == id);

            this.ViewBag._ListaGeneros = generos.OrderBy(x => x.Nome);
            var listaGenerosFilme = filme.Generos;

CineManager/CineManager/Controllers/SalasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineManager.Data;
using CineManager.Models;
using Microsoft.AspNetCore.Authorization;

namespace CineManager.Controllers
{
    [Authorize]
    public class SalasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SalasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Salas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sala.Include(x => x.TipoSala).ToListAsync());
        }

        // GET: Salas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sala = await _context.Sala.Include(x => x.TipoSala)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sala == null)
            {
                return NotFound();
            }

            return View(sala);
        }

        // GET: Salas/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.ListaTipoSalas = await _context.TipoSala.ToListAsync();
            return View();
        }

        // POST: Salas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Sala sala)
        {
            if (ModelState.IsValid)
            {
                _context.Sala.Add(sala);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sala);
        }

        // GET: Salas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sala = await _context.Sala.Include(x => x.TipoSala).FirstOrDefaultAsync(x => x.Id == id);
            if (sala == null)
            {
                return NotFound();
            }
            ViewBag.ListaTipoSalas = await _context.TipoSala.ToListAsync();
            return View(sala);
        }

        // POST: Salas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [FromForm] Sala sala)
        {
            if (id != sala.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sala);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaExists(sala.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sala);
        }

        // GET: Salas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sala = await _context.Sala.Include(x => x.TipoSala)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sala == null)
            {
                return NotFound();
            }

            return View(sala);
        }

        // POST: Salas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sala = await _context.Sala.Include(x => x.TipoSala).FirstOrDefaultAsync(x => x.Id == id);
            _context.Sala.Remove(sala);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalaExists(int id)
        {
            return _context.Sala.Any(e => e.Id == id);
        }
    }
}

CineManager/CineManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cine Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/fontawesome-all.css" rel="stylesheet" />
    <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <link href="~/Template/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet" />

    <link href="~/Template/dist/css/style.css" rel="stylesheet" />

</head>
<body>

    @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CineManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filme" asp-action="Index">Filmes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Salas" asp-action="Index">Salas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sessao" asp-action="Index">Sessões</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    <header class="topbar" data-navbarbg="skin5">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
            <div class="navbar-header bg-warning" data-logobg="skin5">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <b class="logo-icon">
                        <img src="~/Template/assets/images/logo-cm-ps.png" alt="homepage" class="light-logo" />
                    </b>
                </a>

                <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            </div>

            <div class="navbar-collapse collapse bg-warning" id="navbarSupportedContent" data-navbarbg="skin5">

                <ul class="navbar-nav float-left mr-auto">
                    <!-- <li class="nav-item search-box"> <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                    <form class="app-search position-absolute">
                        <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form> -->
                    @*</li>*@
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/Template/assets/images/users/d1.jpg" alt="user" class="rounded-circle" width="31"></a>


                        <div class="dropdown-menu dropdown-menu-right user-dd animated">
                            <partial name="_LoginPartial" />
                        </div>
                    </li>

                </ul>
            </div>
        </nav>
    </header>

    @*<div class="wrapper">*@

    @*<aside class="left-sidebar" data-sidebarbg="skin6">*@

    @*</header>*@
    @*</div>*@



    <table width="100%">
        <tr>
            <td width="20%" valign="top">
                <!-- Sidebar scroll-->
                <div class="scroll-sidebar">
                    <!-- Sidebar -->
                    <nav id="sidebar-nav">
                        <ul id="sidebarnav" style="list-style-type: none;">
                            @*<li>
                                    <div class="user-profile d-flex no-block dropdown m-t-20">
                                        <div class="user-content hide-menu m-l-10">

                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Userdd">
                                                <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user m-r-5 m-l-5"></i> Perfil</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0)"><i class="ti-settings m-r-5 m-l-5"></i>Configurações da Conta</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0)"><i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>*@

                            @*<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" aria-expanded="false" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home" style="color:#f0ad4e"></i><span class="hide-menu">Home</span></a></li>

                                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" aria-expanded="false" asp-area="" asp-controller="Filme" asp-action="Index"><i class="fa fa-film" style="color:#f0ad4e"></i><span class="hide-menu">Filmes</span></a></li>

                                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" aria-expanded="false" asp-area="" asp-controller="Salas" asp-action="Index"><i class="fa fa-list" style="color:#f0ad4e"></i><span class="hide-menu">Salas</span></a></li>

                                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" aria-expanded="false" asp-area="" asp-controller="Sessao" asp-action="Index"><i class="fa fa-calendar" style="color:#f0ad4e"></i><span class="hide-menu">Sessões</span></a></li>

                                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" aria-expanded="false" asp-area="" asp-controller="Funcionario" asp-action="Index"><i class="fa fa-users" style="color:#f0ad4e"></i><span class="hide-menu">Funcionários</span></a></li>

                                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" aria-expanded="false" asp-area="" asp-controller="Fornecedor" asp-action="Index"><i class="fa fa-industry" style="color:#f0ad4e"></i><span class="hide-menu">Fornecedores</span></a></li>*@

                            @if (User.Identity.IsAuthenticated) {
                                <li class="sidebar-item">
                                    <a class="nav-link text-dark" style="font-size:15px; font-weight: bold;" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home" style="color:#f0ad4e; font-size:30px;"></i> Home</a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="nav-link text-dark" style="font-size:15px; font-weight: bold;" asp-area="" asp-controller="Filme" asp-action="Index"><i class="fa fa-film" style="color:#f0ad4e; font-size:30px;"></i> Filmes</a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="nav-link text-dark" style="font-size:15px; font-weight: bold;" asp-area="" asp-controller="Salas" asp-action="Index"><i class="fa fa-list" style="color:#f0ad4e; font-size:30px;"></i> Salas</a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="nav-link text-dark" style="font-size:15px; font-weight: bold;" asp-area="" asp-controller="Sessao" asp-action="Index"><i class="fa fa-calendar" style="color:#f0ad4e; font-size:30px;"></i> Sessões</a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="nav-link text-dark" style="font-size:15px; font-weight: bold;" asp-area="" asp-controller="Funcionario" asp-action="Index"><i class="fa fa-users" style="color:#f0ad4e; font-size:30px;"></i> Funcionários</a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="nav-link text-dark" style="font-size:15px; font-weight: bold;" asp-area="" asp-controller="Fornecedor" asp-action="Index"><i class="fa fa-industry" style="color:#f0ad4e; font-size:30px;"></i> Fornecedores</a>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
                @*</aside>*@
            </td>

            <td width="90%">
                <div class="container-fluid">
                    @*<div>*@
                    @RenderBody()
                    @*</div>*@
                </div>
            </td>
        </tr>
    </table>




    @*<footer class="footer text-muted">
            <div class="container">
                &copy; 2020 - CineManager
            </div>
        </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-mask-plugin/src/jquery.mask.js" type="text/javascript" asp-append-version="true"></script>
    <script src="~/js/consultaCep.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js" type="text/javascript" asp-append-version="true"></script>

    <script src="~/Template/assets/libs/popper.js/dist/umd/popper.min.js"></script>

    <script src="~/Template/dist/js/app-style-switcher.js"></script>

    <script src="~/Template/dist/js/custom.js"></script>
    <script src="~/Template/dist/js/sidebarmenu.js"></script>
    <script src="~/Template/dist/js/waves.js"></script>

    <script src="~/Template/assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="~/Template/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/Template/dist/js/pages/dashboards/dashboard1.js"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>